
openapi: 3.0.1
info:
  title: ProductReview API
  description: API for create, read/retrieve, update and delete users, categories, reviews
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local server  
paths:
  /user/login:
    post:
      summary: User login
      description: Validate user credentials and return a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's username
                password:
                  type: string
                  description: User's password
              required:
                - email
                - password
      responses:
        200:
          description: User successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        400:
          description: Invalid user credentials
          content:
            application/json:
              schema:
                type: string
              example: Bad Request
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
  /user/name:
    get:
      summary: Get user name by user ID
      description: Retrieve the user's name based on their ID. Requires a valid JWT token in the Authorization header.
      parameters:
        - name: id
          in: query
          description: The UUID of the user
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer token for authorization
          required: true
          schema:
            type: string
      responses:
        200:
          description: User name retrieved successfully
          content:
            application/json:
              schema:
                type: string
                example: Jonas S.
        400:
          description: Invalid Authorization header or bad UUID format
          content:
            application/json:
              schema:
                type: string
              examples:
                missing_header:
                  value: Authorization header must be provided and start with 'Bearer '.
                bad_uuid:
                  value: ""
        401:
          description: Invalid or expired JWT token
          content:
            application/json:
              schema:
                type: string
              example: Invalid or expired JWT token.
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: string

  /user/add:
    post:
      summary: Add a new user
      description: Adds a new user to the system. Accepts user details in the request body and a `acceptnews` flag as a query parameter.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: Unique identifier for the user.
                name:
                  type: string
                  description: The name of the user.
                email:
                  type: string
                  format: email
                  description: The email address of the user.
                password:
                  type: string
                  format: password
                  description: The password for the user account.
                role:
                  type: string
                  description: The role assigned to the user (e.g., ADMIN, USER).
              required:
                - name
                - email
                - password
      parameters:
        - name: acceptnews
          in: query
          required: true
          description: A boolean indicating whether the user accepts news subscriptions.
          schema:
            type: boolean
      responses:
        '200':
          description: User added successfully.
          content:
            application/json:
              schema:
                type: string
        '409':
          description: Conflict. The user's email already exists.
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error. An error occurred while adding the user.
          content:
            application/json:
              schema:
                type: string

  /categories/all:
    get:
      summary: Get all categories
      description: Retrieve a list of all category names. Requires a valid JWT token in the Authorization header.
      parameters:
        - name: Authorization
          in: header
          description: Bearer token for authorization
          required: true
          schema:
            type: string
      responses:
        200:
          description: Categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Category name
        400:
          description: Invalid Authorization header
          content:
            application/json:
              schema:
                type: string
              example: Authorization header must be provided and start with 'Bearer '.
        401:
          description: Invalid or expired JWT token
          content:
            application/json:
              schema:
                type: string
              example: Invalid or expired JWT token.
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: string            
  /reviews/category:
    get:
      summary: Get reviews by category
      description: Retrieve reviews based on the specified category. Requires a valid JWT token in the Authorization header.
      parameters:
        - name: category
          in: query
          description: The category of reviews to retrieve
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer token for authorization
          required: true
          schema:
            type: string
      responses:
        200:
          description: Reviews retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Review ID
                    userId:
                      type: string
                      format: uuid
                      description: User ID associated with the review
                    categoryId:
                      type: integer
                      description: Category ID
                    productName:
                      type: string
                      description: Product name reviewed
                    reviewText:
                      type: string
                      description: Review text
                    rating:
                      type: integer
                      description: Rating given to the product
                    photo:
                      type: string
                      format: byte
                      description: Photo associated with the review
                    createdAt:
                      type: string
                      format: date-time
                      description: Timestamp when the review was created
        400:
          description: Invalid Authorization header
          content:
            application/json:
              schema:
                type: string
              example: Authorization header must be provided and start with 'Bearer '.
        401:
          description: Invalid or expired JWT token
          content:
            application/json:
              schema:
                type: string
              example: Invalid or expired JWT token.
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
  /reviews/add:
    post:
      summary: Add a new review
      description: Adds a review with an optional image
      parameters:
        - name: category
          in: query
          description: The review product category
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer token for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                review:
                  type: string
                  description: JSON string containing review details (productName, reviewText, rating)
                  example: '{"productName": "Sample Product", "reviewText": "Great product!", "rating": 5}'
                image:
                  type: string
                  format: binary
                  description: Image file associated with the review
      responses:
        '200':
          description: Review added successfully
          content:
            application/json:
              schema:
                type: string
                example: success
        '400':
          description: Invalid authorization header
          content:
            application/json:
              schema:
                type: string
                example: Authorization header must be provided and start with 'Bearer '.
        '401':
          description: Invalid or expired JWT token
          content:
            application/json:
              schema:
                type: string
                example: Invalid or expired JWT token.
        '406':
          description: Review creation failed
          content:
            application/json:
              schema:
                type: string
                example: failed
  /review/delete:
    delete:
      summary: Delete a review by ID
      description: Deletes a review based on the provided `reviewId`. Requires valid `Authorization` header.
      parameters:
        - name: reviewId
          in: query
          description: The ID of the review to be deleted
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: Bearer token for authorization
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: "success"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                example: "You do not have permission to perform this action."
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
                example: "Review not found."
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                example: "Invalid or missing authorization header."
  /review/search:
    get:
      summary: Retrieve reviews by search text
      description: Retrieves reviews that match the provided search text. Requires an Authorization header with a valid token.
      parameters:
        - name: searchtext
          in: query
          required: true
          description: The search text used to filter reviews.
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authorization.
          schema:
            type: string
      responses:
        '200':
          description: A list of reviews matching the search criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Review ID
                    userId:
                      type: string
                      format: uuid
                      description: User ID associated with the review
                    categoryId:
                      type: integer
                      description: Category ID
                    productName:
                      type: string
                      description: Product name reviewed
                    reviewText:
                      type: string
                      description: Review text
                    rating:
                      type: integer
                      description: Rating given to the product
                    photo:
                      type: string
                      format: byte
                      description: Photo associated with the review
                    createdAt:
                      type: string
                      format: date-time
                      description: Timestamp when the review was created
        '400':
          description: Bad request or no matching reviews found.
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized access. Invalid or missing authorization header.
          content:
            application/json:
              schema:
                type: string
  /review/user:
    get:
      summary: Retrieve all reviews created by the logged-in user
      description: Retrieves all reviews created by the user associated with the provided JWT in the `Authorization` header.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authorization.
          schema:
            type: string
      responses:
        '200':
          description: A list of reviews created by the logged-in user.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Review ID
                    userId:
                      type: string
                      format: uuid
                      description: User ID associated with the review
                    categoryId:
                      type: integer
                      description: Category ID
                    productName:
                      type: string
                      description: Product name reviewed
                    reviewText:
                      type: string
                      description: Review text
                    rating:
                      type: integer
                      description: Rating given to the product
                    photo:
                      type: string
                      format: byte
                      description: Photo associated with the review
                    createdAt:
                      type: string
                      format: date-time
                      description: Timestamp when the review was created
        '400':
          description: Bad request or no reviews found for the user.
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized access. Invalid or missing authorization header.
          content:
            application/json:
              schema:
                type: string